site_name: Octos
site_url: https://underpig1.github.io/octos/docs/
repo_url: https://github.com/underpig1/octos
edit_uri: tree/master/docs
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: black
      accent: custom
  favicon: img/icon.ico
  logo: img/icon.ico
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.highlight
    - navigation.footer
    - content.action.edit
    # - announce.dismiss
plugins:
  - search
  # - git-revision-date-localized:
  #     fallback_to_build_date: false
  - git-revision-date-localized
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css
extra:
  analytics:
    provider: umami
    property: 416a23b5-11a1-49f5-9877-24803f746146
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: octicons/thumbsup-24
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: octicons/thumbsdown-24
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            submitting an <a href="https://github.com/underpig1/octos/issues/new" target="_blank" rel="noopener">issue</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/underpig1/octos
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/octos
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     This site uses cookies to measure the effectiveness of our documentation and count metrics like page views and downloads. With your consent, you're helping us make Octos better.
  #   actions:
  #     - accept
  #     - manage
copyright: >
  Copyright &copy; 2025 underpig1
#  - <a href="https://underpig1.github.io/octos/about/privacy/">Privacy policy</a>
nav:
  - Home: index.md
  - Quickstart:
      - Installation: install.md
  - Guides:
      - guides/index.md
      - Making a mod: guides/mod.md
      - Using the API: guides/api.md
      - Using the CLI: guides/cli.md
      - Adding user options: guides/options.md
      - octos.json: guides/config.md
      - Publishing your mod: guides/publish.md
      - Tips and tricks: guides/tips.md
  - API Reference:
      - reference/index.md
      - MediaController: reference/mediacontroller.md
      - MonitorBridge: reference/monitorbridge.md
      - System: reference/system.md
      - UserOptions: reference/useroptions.md
  - About:
      - Contributing: about/contributing.md
      - Code of Conduct: about/conduct.md
      - Support: about/support.md
      - Roadmap: about/roadmap.md
      - License: about/license.md
      - Privacy policy: about/privacy.md
      # - Privacy policy: about/privacy.md
      - Support: about/support.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: false
      auto_title: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/javascript.min.js
  - js/extra.js
