name: Build
on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "Octos.vcxproj"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "Octos.vcxproj"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild env
        uses: microsoft/setup-msbuild@v2
      - name: Install dependencies or restore cache
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false
      - name: Build
        run: msbuild Octos.vcxproj /p:Configuration=Release /p:VcpkgRoot="%VCPKG_ROOT%"