name: App
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      run: vcpkg install
    - name: Build app
      run: msbuild
      env:
        VCPKG_ROOT: C:\vcpkg
        CMAKE_TOOLCHAIN_FILE: C:\vcpkg\scripts\buildsystems\vcpkg.cmake
    # - name: Archive executable
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: MyApp.exe
    #     path: build\MyApp.exe