name: Package
on:
  push:
    branches:
      - master
jobs:
  build-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build EXE
        run: msbuild /t:InnoSetup
      - name: Build MSIX
        run: msbuild /t:BundleAppx