name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  create-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Extract version from tag (dev)
        if: github.event_name == 'workflow_dispatch'
        run: echo "VERSION=0.0.0" >> $env:GITHUB_ENV
      
      - name: Extract version from tag
        if: github.ref_type == 'tag'
        run: echo "VERSION=$($env:GITHUB_REF -replace 'refs/tags/v','')" >> $env:GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: npm install
      - name: Update package version
        run: npm version $env:VERSION --no-git-tag-version
      - name: Build API
        run: npm run build-api
      - name: Publish as npm package
        if: github.ref_type == 'tag'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup MSBuild env
        uses: microsoft/setup-msbuild@v2
      - name: Install dependencies or restore cache
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: true
      - name: Integrate vcpkg
        run: vcpkg integrate install
      - name: Build
        run: msbuild Octos.vcxproj /t:InnoSetup /p:AppVersion=$env:VERSION.0
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: octos.min.js build/OctosSetup.exe LICENSE #build/OctosSetup.msixbundle #build/appx/*
          body_path: ./.github/CHANGELOG.md